### ISSUE TITLE
Не работает в CentOS 5

### ISSUE THREAD

**Issue by Zenitur** [figec/ttyhlauncher#22]
Я подготовил среду сборки в CentOS 5 по этому руководству: http://qt-project.org/forums/viewthread/38354 Скомпилировал Qt 5, quazip и ttyhlauncher. В итоге лаунчер работает как в CentOS 5, так и в любом другом дистрибутиве Linux. Но из-за ошибки "Error: JSON: invalid UTF8 string at 50" не удаётся залогиниться.

Вот лог запуска:

[zenitur@localhost ttyhlauncher]$ ./run_game.sh 
QXcbConnection: Failed to initialize XRandr
(17:06:53) Logger >> 21.01.15 ttyhlauncher-0.9 started.
(17:06:54) Settings >> Updating local clisent list...
(17:06:54) Util >> Make GET: http://store.ttyh.ru/prefixes.json
(17:06:54) Settings >> OK. Saving local copy...
(17:06:54) Settings >> Loading local client list...
(17:06:54) Settings >> Error: JSON: invalid UTF8 string at 50
(17:06:54) Settings >> Updating local java keystore...
(17:06:54) Util >> Make GET: http://store.ttyh.ru/store.ks
(17:06:54) Settings >> OK. Saving local copy...
(17:06:55) LauncherWindow >> Launcher window opened

Вот сама сборка: https://yadi.sk/d/NCHkp4i0dspvu

Что пробовал: сборку с ICU, с SSL 1.0.1 вместо 0.9.8, и запускать бинарник в современном дистрибутиве Linux.

**Comment by aimlol** [comment]
Версия Qt выше 5.3?

**Comment by Zenitur** [comment]
aimlol, да - 5.3.2. Пришлось дополнить инструкцию доустановкой libxslt и python26.

**Comment by figec** [comment]
Судя по сообщению об ошибке, оно валится на кириллице:
```
$ head -c 51 prefixes.json 
{
  "prefixes": {
    "default": {
      "about": "
```
Ошибка всплывает тут: https://github.com/qtproject/qtbase/blob/dev/src/corelib/json/qjsonparser.cpp#L863
А происходит это при вызове: https://github.com/qtproject/qtbase/blob/5180f32c5abe01acd65cde68c2c16aedda4028ec/src/corelib/codecs/qutfcodec_p.h#L178

Не знаю по какой причине у тебя не работает эта функция, но похоже ты собрал Qt слишком урезано, без поддержки мультибайтовых кодировок.

Нужна поддержка `QUTFCODEC`, насколько я понял. который ещё и `is not part of the Qt API`, как написано в сорцах.

**Comment by Zenitur** [comment]
figec, "собрал Qt слишком урезано" да, так и есть - я использовал патчи для отвязывания Webkit от ICU. http://pkgs.fedoraproject.org/cgit/mingw-qt5-qtwebkit.git/tree/ Их нашёл в интернете Derlaff. https://www.linux.org.ru/forum/development/10807986?cid=10808141 ICU - оно же для Юникода, причина может вполне быть в этом.

Вот только в новом дистрибутиве Qt собран без ICU, и ничего. А в старом собрать с ICU я тоже пробовал, и тоже не помогло.

"Насколько я понял, нужна поддержка QUTFCODEC" Щас буду искать и включать :-) Спасибо. Если всё получится - я испытаю оргазм! Четвёртую ночь уже долблю этот Qt.

**Comment by figec** [comment]
Судя по https://www.linux.org.ru/forum/development/11203363 ты хочешь сделать portable-версию, тогда советую тебе совсем выпилить вебкитовую часть, но придётся делать форк (так уже делал Brain).

**Comment by Zenitur** [comment]
Мне кажется что отказ от Webkit не поможет. Ошибка же в Qtbase, а точнее qtbase/src/corelib/json/

Сейчас посмотрел - знакомый путь к файлу. Один из патчей, необходимый для успешной компиляции в старой системе, исправляет файл qtbase/src/corelib/tools/qmap.h. Патч можно найти поиском слова "corelib" по странице http://qt-project.org/forums/viewthread/38354 Я предположил что патч кривой и наколенный, погуглил ошибку, которая возникает без него. Применил вместо того патча этот: https://codereview.qt-project.org/#/c/61409/2/src/corelib/tools/qmap.h Не помогло.

Перехожу к крайним мерам - компиляция в GCC 4.7 вместо 4.4. Тут главное чтобы GLIBC был 2.4-2.5, а C++ Runtime (libgcc_s.so.1 и libstdc++.so.6) можно таскать с приложением.

**Comment by nexfwall** [comment]
Лол, Зенитур. Ты бы на еще под Debian 5 собрал. Или под еще более 
древнее говно.
Чем поддержка CentOS 6 не угодила?

21.01.2015 20:15, Zenitur пишет:

**Comment by derlaft** [comment]
>да, так и есть - я использовал патчи для отвязывания Webkit от ICU. http://pkgs.fedoraproject.org/cgit/mingw-qt5-qtwebkit.git/tree/ Их нашёл в интернете Derlafff

Патчи-то патчами, но саму поддержку юникода ты включил при сборке? Если да, то не имею понятия, от чего это.

**Comment by Zenitur** [comment]
РЕШЕНО

Собрал с помощью GCC 4.7. http://i.imgur.com/NAaF4IL.png Протестируйте, пожалуйста, ссылочку во всех дистрибутивах Linux, которые у вас есть: https://yadi.sk/d/NCHkp4i0dspvu Там только нет нескольких последних коммитов. Когда соберу 64-битную сборку, и когда все протестируют в своих дистрибутивах Linux, можно будет вывесить на "главную".

**Comment by figec** [comment]
Ок. Закрываю.
